# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160913_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
