# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20160915_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
