# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20160916_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_age',
            field=models.CharField(max_length=100),
        ),
    ]
